StudentsApp.WebUI/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using StudentsApp.ApplicationServices.Services;
using StudentsApp.ApplicationServices.ViewModels;
using StudentsApp.DomainModel.Entities;
using StudentsApp.DomainModel.Repositories;
using StudentsApp.WebUI.Filters;

namespace StudentsApp.WebUI.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentAppService _studentAppService;
        private readonly IStudentRepository _studentRepository;

        public StudentController(IStudentAppService studentAppService,
            IStudentRepository studentRepository)
        {
            _studentAppService = studentAppService;
            _studentRepository = studentRepository;
        }

        public ActionResult List()
        {
            var students = _studentAppService.GetAllStudents();
            return new JsonResult
            {
                Data = new
                {
                    data = students
                },
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        //
        // GET: /Student/Details/5
        [IsAuthorized(RoleType = RoleType.Student)]
        public ActionResult Details(int id)
        {
            StudentDetailsViewModel studentDetails = _studentAppService.GetStudentDetails(id);

            return PartialView(studentDetails);
        }

        //
        // GET: /Student/Create
        [IsAuthorized(RoleType = RoleType.Dean)]
        public ActionResult Create()
        {
            return PartialView(new StudentDetailsViewModel());
        }

        //
        // POST: /Student/Create
        [HttpPost]
        [IsAuthorized(RoleType = RoleType.Dean)]
        public ActionResult Create(StudentDetailsViewModel studentViewModel)
        {
            if (ModelState.IsValid)
            {
                SaveResultViewModel saveResult = _studentAppService.RegisterStudent(studentViewModel);

                return Json(saveResult);
            }

            return Json(new SaveResultViewModel()
            {
                IsSuccess = false,
                Message = "Введенные данные не корректны"
            });
        }

        //
        // GET: /Student/Edit/5
        [IsAuthorized(RoleType = RoleType.Dean)]
        public ActionResult Edit(int id)
        {
            StudentDetailsViewModel studentDetails = _studentAppService.GetStudentDetails(id);

            return PartialView(studentDetails);
        }

        //
        // POST: /Student/Edit/5
        [HttpPost]
        [IsAuthorized(RoleType = RoleType.Dean)]
        public ActionResult Edit(StudentDetailsViewModel studentViewModel)
        {
            if (ModelState.IsValid)
            {
                SaveResultViewModel saveResult = _studentAppService.SaveStudent(studentViewModel);

                return Json(saveResult);
            }

            return Json(new SaveResultViewModel()
            {
                IsSuccess = false,
                Message = "Введенные данные не корректны"
            });
        }

    }
}

StudentsApp.WebUI/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StudentsApp.ApplicationServices.Services.Impl;
using StudentsApp.ApplicationServices.ViewModels;
using StudentsApp.DomainModel.Entities;
using StudentsApp.WebUI.Filters;

namespace StudentsApp.WebUI.Controllers
{
    public class TeacherController : Controller
    {
        private readonly TeacherAppService _teacherAppService;

        public TeacherController(TeacherAppService teacherAppService)
        {
            _teacherAppService = teacherAppService;
        }

        public ActionResult List()
        {
            var teachers = _teacherAppService.GetAllTeachers();
            return new JsonResult
            {
                Data = new
                {
                    data = teachers
                },
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        [IsAuthorized(RoleType = RoleType.Dean)]
        public ActionResult TeachersThatCanBeAdded(int studentId)
        {
            IEnumerable<TeacherViewModel> teachers = 
                _teacherAppService.GetAllTeachersExceptStudentTeachers(studentId);

            return new JsonResult
            {
                Data = new
                {
                    items = teachers
                },
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        //
        // GET: /Teacher/Details/5
        [IsAuthorized(RoleType = RoleType.Teacher)]
        public ActionResult Details(int id)
        {
            TeacherDetailsViewModel teacherDetails = _teacherAppService.GetTeacherDetails(id);

            return PartialView(teacherDetails);
        }

        //
        // GET: /Teacher/Create
        [IsAuthorized(RoleType = RoleType.Dean)]
        public ActionResult Create()
        {
            return PartialView(new TeacherDetailsViewModel());
        }

        //
        // POST: /Teacher/Create
        [HttpPost]
        [IsAuthorized(RoleType = RoleType.Dean)]
        public ActionResult Create(TeacherDetailsViewModel teacherDetailsViewModel)
        {
            if (ModelState.IsValid)
            {
                SaveResultViewModel saveResult = _teacherAppService.RegisterTeacher(teacherDetailsViewModel);

                return Json(saveResult);
            }

            return Json(new SaveResultViewModel()
            {
                IsSuccess = false,
                Message = "Введенные данные не корректны"
            });
        }

        //
        // GET: /Teacher/Edit/5
        [IsAuthorized(RoleType = RoleType.Dean)]
        public ActionResult Edit(int id)
        {
            TeacherDetailsViewModel teacherDetails = _teacherAppService.GetTeacherDetails(id);

            return PartialView(teacherDetails);
        }

        //
        // POST: /Teacher/Edit/5
        [HttpPost]
        [IsAuthorized(RoleType = RoleType.Dean)]
        public ActionResult Edit(TeacherDetailsViewModel teacherDetailsViewModel)
        {
            if (ModelState.IsValid)
            {
                SaveResultViewModel saveResult = _teacherAppService.SaveTeacher(teacherDetailsViewModel);

                return Json(saveResult);
            }

            return Json(new SaveResultViewModel()
            {
                IsSuccess = false,
                Message = "Введенные данные не корректны"
            });
        }
    }
}

StudentsApp.WebUI/Views/Teacher/Create.cshtml
@model StudentsApp.ApplicationServices.ViewModels.TeacherDetailsViewModel

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "form-create-teacher" })) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control input-sm" })
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SurName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.SurName, new { @class = "form-control input-sm" })
                @Html.ValidationMessageFor(model => model.SurName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubjectName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.SubjectName, new { @class = "form-control input-sm" })
                @Html.ValidationMessageFor(model => model.SubjectName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Students, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div id="create-modal-add-student" class="modal fade" role="dialog">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title">Добавление студента</h4>
                            </div>
                            <div class="modal-body">
                                <select id="create-select-students">
                                    <option></option>
                                </select>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                                <button id="create-btn-add-student" type="button" class="btn btn-primary">
                                    Добавить студента
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                <input id="create-btn-open-add-student-modal" type="button" value="Добавить" class="btn-add btn-sm btn-default" data-toggle="modal" />
                <table id="create-studentStudentsTable" class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>Фамилия, Имя</th>
                        </tr>
                    </thead>
                    @for (int i = 0; i < Model.Students.Count(); i++)
                    {
                        <tr>
                            <td>
                                @{
                                    var student = Model.Students[i];
                                }
                                @Html.DisplayFor(modelItem => student.FullName)
                            </td>
                            @Html.HiddenFor(modelItem => modelItem.Students[i].StudentUserId)
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
}


<script type="text/javascript">
    $(document).ready(function () {
        $(document).on('click', '#create-btn-open-add-student-modal', function () {
            $.ajax({
                url: '@Url.Action("List", "Student")',
                success: function (data) {
                    var select2Data = $.map(data.data, function (obj) {
                        obj.id = obj.StudentUserId;
                        obj.text = obj.StudentFullName;
                        return obj;
                    });
                    console.log(select2Data);
                    $("#create-select-students").select2({
                        placeholder: "Выбрать студента",
                        data: select2Data,
                        width: 300
                    });
                    $('#create-modal-add-student').modal('show');
                }
            });
        });

        $(document).on('click', '#create-btn-add-student', function () {
            var selectedOption = $("#create-select-students").select2('data')[0];
            if (selectedOption.id) {
                var studentCount = $('#create-studentStudentsTable > tbody > tr').length;
                var studentUserIdHidden =
                    '<input type="hidden" ' +
                        'value="' + selectedOption.id + '" ' +
                        'name="Students[' + studentCount + '].StudentUserId">' +
                    '</input>';

                var teacherFullName = selectedOption.text;
                $('#create-studentStudentsTable').append('<tr><td>' + teacherFullName + '</td>' + studentUserIdHidden + '</tr>');
                window.CloseDialog('create-modal-add-student');
            }
        });
    });
</script>

StudentsApp.WebUI/Views/Teacher/Details.cshtml
@model StudentsApp.ApplicationServices.ViewModels.TeacherDetailsViewModel

<div id="modal-view-student" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Профиль преподавателя</h4>
            </div>
            <div class="modal-body">
                <div>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Login)
                        </dt>

                        <dd>
                            <div class="col-md-10">
                                @Html.DisplayFor(model => model.Login)
                            </div>
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.FirstName)
                        </dt>

                        <dd>
                            <div class="col-md-10">
                                @Html.DisplayFor(model => model.FirstName)
                            </div>
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.SurName)
                        </dt>

                        <dd>
                            <div class="col-md-10">
                                @Html.DisplayFor(model => model.SurName)
                            </div>
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.SubjectName)
                        </dt>

                        <dd>
                            <div class="col-md-10">
                                @Html.DisplayFor(model => model.SubjectName)
                            </div>
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Students)
                        </dt>

                        <dd>
                            <div class="col-md-10">
                                <table id="details-teacherStudentsTable" class="table table-striped table-bordered table-hover">
                                    <thead>
                                        <tr>
                                            <th>Фамилия</th>
                                            <th>Имя</th>
                                        </tr>
                                    </thead>
                                    @foreach (var student in Model.Students)
                                    {
                                        <tr>
                                            <td>@student.SurName</td>
                                            <td>@student.FirstName</td>
                                        </tr>
                                    }
                                </table>
                            </div>
                        </dd>
                    </dl>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">ОК</button>
            </div>
        </div>
    </div>
</div>

StudentsApp.WebUI/Views/Teacher/Edit.cshtml
@model StudentsApp.ApplicationServices.ViewModels.TeacherDetailsViewModel

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "form-edit-teacher" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.TeacherUserId)
        
        <div class="form-group form-group-sm">
            @Html.LabelFor(model => model.Login, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Login, new { @class = "form-control input-sm" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control input-sm" })
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SurName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.SurName, new { @class = "form-control input-sm" })
                @Html.ValidationMessageFor(model => model.SurName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubjectName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.SubjectName, new { @class = "form-control input-sm" })
                @Html.ValidationMessageFor(model => model.SubjectName)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Students, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div id="modal-add-student" class="modal fade" role="dialog">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title">Добавление студента</h4>
                            </div>
                            <div class="modal-body">
                                <select id="select-students">
                                    <option></option>
                                </select>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                                <button id="btn-add-student" type="button" class="btn btn-primary">
                                    Добавить студента
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                <input id="btn-open-add-student-modal" type="button" value="Добавить" class="btn-add btn-sm btn-default" data-toggle="modal" />
                <table id="studentStudentsTable" class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>Фамилия, Имя</th>
                        </tr>
                    </thead>
                    @for (int i = 0; i < Model.Students.Count(); i++)
                    {
                        <tr>
                            <td>
                                @{
                                    var student = Model.Students[i];
                                }
                                @Html.DisplayFor(modelItem => student.FullName)
                            </td>
                            @Html.HiddenFor(modelItem => modelItem.Students[i].StudentUserId)
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
}


<script type="text/javascript">
    $(document).ready(function () {
        $(document).on('click', '#btn-open-add-student-modal', function () {
            $.ajax({
                url: '@Url.Action("List", "Student")',
                success: function (data) {
                    var select2Data = $.map(data.data, function (obj) {
                        obj.id = obj.StudentUserId;
                        obj.text = obj.StudentFullName;
                        return obj;
                    });
                    console.log(select2Data);
                    $("#select-students").select2({
                        placeholder: "Выбрать студента",
                        data: select2Data,
                        width: 300
                    });
                    $('#modal-add-student').modal('show');
                }
            });
        });

        $(document).on('click', '#btn-add-student', function () {
            var selectedOption = $("#select-students").select2('data')[0];
            if (selectedOption.id) {
                var studentCount = $('#studentStudentsTable > tbody > tr').length;
                var studentUserIdHidden =
                    '<input type="hidden" ' +
                        'value="' + selectedOption.id + '" ' +
                        'name="Students[' + studentCount + '].StudentUserId">' +
                    '</input>';

                var teacherFullName = selectedOption.text;
                $('#studentStudentsTable').append('<tr><td>' + teacherFullName + '</td>' + studentUserIdHidden + '</tr>');
                window.CloseDialog('modal-add-student');
            }
        });
    });
</script>