StudentsApp.WebUI/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using StudentsApp.ApplicationServices.Services;
using StudentsApp.ApplicationServices.ViewModels;
using StudentsApp.DomainModel.Entities;
using StudentsApp.DomainModel.Repositories;
using StudentsApp.WebUI.Filters;

namespace StudentsApp.WebUI.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentAppService _studentAppService;
        private readonly IStudentRepository _studentRepository;

        public StudentController(IStudentAppService studentAppService,
            IStudentRepository studentRepository)
        {
            _studentAppService = studentAppService;
            _studentRepository = studentRepository;
        }

        public ActionResult List()
        {
            var students = _studentAppService.GetAllStudents();
            return new JsonResult
            {
                Data = new
                {
                    data = students
                },
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        //
        // GET: /Student/Details/5
        [IsAuthorized(RoleType = RoleType.Student)]
        public ActionResult Details(int id)
        {
            StudentDetailsViewModel studentDetails = _studentAppService.GetStudentDetails(id);

            return PartialView(studentDetails);
        }

        //
        // GET: /Student/Create
        [IsAuthorized(RoleType = RoleType.Dean)]
        public ActionResult Create()
        {
            return PartialView(new StudentDetailsViewModel());
        }

        //
        // POST: /Student/Create
        [HttpPost]
        [IsAuthorized(RoleType = RoleType.Dean)]
        public ActionResult Create(StudentDetailsViewModel studentViewModel)
        {
            if (ModelState.IsValid)
            {
                SaveResultViewModel saveResult = _studentAppService.RegisterStudent(studentViewModel);

                return Json(saveResult);
            }

            return Json(new SaveResultViewModel()
            {
                IsSuccess = false,
                Message = "Введенные данные не корректны"
            });
        }

        //
        // GET: /Student/Edit/5
        [IsAuthorized(RoleType = RoleType.Dean)]
        public ActionResult Edit(int id)
        {
            StudentDetailsViewModel studentDetails = _studentAppService.GetStudentDetails(id);

            return PartialView(studentDetails);
        }

        //
        // POST: /Student/Edit/5
        [HttpPost]
        [IsAuthorized(RoleType = RoleType.Dean)]
        public ActionResult Edit(StudentDetailsViewModel studentViewModel)
        {
            if (ModelState.IsValid)
            {
                SaveResultViewModel saveResult = _studentAppService.SaveStudent(studentViewModel);

                return Json(saveResult);
            }

            return Json(new SaveResultViewModel()
            {
                IsSuccess = false,
                Message = "Введенные данные не корректны"
            });
        }

    }
}

StudentsApp.WebUI/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StudentsApp.ApplicationServices.Services.Impl;
using StudentsApp.ApplicationServices.ViewModels;
using StudentsApp.DomainModel.Entities;
using StudentsApp.WebUI.Filters;

namespace StudentsApp.WebUI.Controllers
{
    public class TeacherController : Controller
    {
        private readonly TeacherAppService _teacherAppService;

        public TeacherController(TeacherAppService teacherAppService)
        {
            _teacherAppService = teacherAppService;
        }

        public ActionResult List()
        {
            var teachers = _teacherAppService.GetAllTeachers();
            return new JsonResult
            {
                Data = new
                {
                    data = teachers
                },
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        [IsAuthorized(RoleType = RoleType.Dean)]
        public ActionResult TeachersThatCanBeAdded(int studentId)
        {
            IEnumerable<TeacherViewModel> teachers = 
                _teacherAppService.GetAllTeachersExceptStudentTeachers(studentId);

            return new JsonResult
            {
                Data = new
                {
                    items = teachers
                },
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        //
        // GET: /Teacher/Details/5
        [IsAuthorized(RoleType = RoleType.Teacher)]
        public ActionResult Details(int id)
        {
            TeacherDetailsViewModel teacherDetails = _teacherAppService.GetTeacherDetails(id);

            return PartialView(teacherDetails);
        }

        //
        // GET: /Teacher/Create
        [IsAuthorized(RoleType = RoleType.Dean)]
        public ActionResult Create()
        {
            return PartialView(new TeacherDetailsViewModel());
        }

        //
        // POST: /Teacher/Create
        [HttpPost]
        [IsAuthorized(RoleType = RoleType.Dean)]
        public ActionResult Create(TeacherDetailsViewModel teacherDetailsViewModel)
        {
            if (ModelState.IsValid)
            {
                SaveResultViewModel saveResult = _teacherAppService.RegisterTeacher(teacherDetailsViewModel);

                return Json(saveResult);
            }

            return Json(new SaveResultViewModel()
            {
                IsSuccess = false,
                Message = "Введенные данные не корректны"
            });
        }

        //
        // GET: /Teacher/Edit/5
        [IsAuthorized(RoleType = RoleType.Dean)]
        public ActionResult Edit(int id)
        {
            TeacherDetailsViewModel teacherDetails = _teacherAppService.GetTeacherDetails(id);

            return PartialView(teacherDetails);
        }

        //
        // POST: /Teacher/Edit/5
        [HttpPost]
        [IsAuthorized(RoleType = RoleType.Dean)]
        public ActionResult Edit(TeacherDetailsViewModel teacherDetailsViewModel)
        {
            if (ModelState.IsValid)
            {
                SaveResultViewModel saveResult = _teacherAppService.SaveTeacher(teacherDetailsViewModel);

                return Json(saveResult);
            }

            return Json(new SaveResultViewModel()
            {
                IsSuccess = false,
                Message = "Введенные данные не корректны"
            });
        }
    }
}

StudentsApp.WebUI/Views/Student/Create.cshtml
@model StudentsApp.ApplicationServices.ViewModels.StudentDetailsViewModel
@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "form-create-student" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true)

        @Html.HiddenFor(model => model.StudentUserId)

        <div class="form-group form-group-sm">
            @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control input-sm" })
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>
        </div>

        <div class="form-group form-group-sm">
            @Html.LabelFor(model => model.SurName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.SurName, new { @class = "form-control input-sm" })
                @Html.ValidationMessageFor(model => model.SurName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Teachers, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div id="create-modal-add-teacher" class="modal fade" role="dialog">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title">Добавление преподавателя</h4>
                            </div>
                            <div class="modal-body">
                                <select id="create-select-teachers">
                                    <option></option>
                                </select>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                                <button id="create-btn-add-teacher" type="button" class="btn btn-primary">
                                    Добавить преподавателя
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                <input id="btn-open-add-teacher-create-modal" type="button" value="Добавить" class="btn-add btn-sm btn-default" data-toggle="modal" />
                <table id="create-studentTeachersTable" class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>Фамилия, Имя</th>
                        </tr>
                    </thead>
                    @for (int i = 0; i < Model.Teachers.Count(); i++)
                    {
                        <tr>
                            <td>
                                @{
                        var teacher = Model.Teachers[i];
                                }
                                @Html.DisplayFor(modelItem => teacher.FullName)
                            </td>
                            @Html.HiddenFor(modelItem => modelItem.Teachers[i].TeacherUserId)
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $(document).ready(function () {
        $(document).on('click', '#btn-open-add-teacher-create-modal', function () {
            $.getJSON('@Url.Action("TeachersThatCanBeAdded", "Teacher", new { studentId = Model.StudentUserId })', function (data) {
                var select2Data = $.map(data.items, function (obj) {
                    obj.id = obj.TeacherUserId;
                    obj.text = obj.SurName + ' ' + obj.FirstName;
                    return obj;
                });
                $("#create-select-teachers").select2({
                    placeholder: "Выбрать преподавателя",
                    data: select2Data,
                    width: 300
                });
                $('#create-modal-add-teacher').modal('show');
            });
        });

        $(document).on('click', '#create-btn-add-teacher', function () {
            var selectedOption = $("#create-select-teachers").select2('data')[0];
            if (selectedOption) {
                var teacherCount = $('#create-studentTeachersTable > tbody > tr').length;
                var teacherUserIdHidden = '<input type="hidden" value="' + selectedOption.id
                    + '" name="Teachers[' + teacherCount + '].TeacherUserId"></input>';
                var teacherFullName = selectedOption.text;
                $('#create-studentTeachersTable').append('<tr><td>' + teacherFullName + '</td>' + teacherUserIdHidden + '</tr>');
                window.CloseDialog('create-modal-add-teacher');
            }
        });
    });
</script>

StudentsApp.WebUI/Views/Student/Details.cshtml
@using StudentsApp.ApplicationServices.ViewModels
@model StudentsApp.ApplicationServices.ViewModels.StudentDetailsViewModel

@{
    ViewBag.Title = "Details";
}

<div id="modal-view-student" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Профиль студента</h4>
            </div>
            <div class="modal-body">
                <div>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Login)
                        </dt>

                        <dd>
                            <div class="col-md-10">
                                @Html.DisplayFor(model => model.Login)
                            </div>
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.FirstName)
                        </dt>

                        <dd>
                            <div class="col-md-10">
                                @Html.DisplayFor(model => model.FirstName)
                            </div>
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.SurName)
                        </dt>

                        <dd>
                            <div class="col-md-10">
                                @Html.DisplayFor(model => model.SurName)
                            </div>
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Teachers)
                        </dt>
                        <dd>
                            <div class="col-md-10">
                                <table id="details-studentTeachersTable" class="table table-striped table-bordered table-hover">
                                    <thead>
                                        <tr>
                                            <th>Фамилия</th>
                                            <th>Имя</th>
                                        </tr>
                                    </thead>
                                    @foreach (var teacher in Model.Teachers)
                                    {
                                        <tr>
                                            <td>@teacher.SurName</td>
                                            <td>@teacher.FirstName</td>
                                        </tr>
                                    }
                                </table>
                            </div>
                        </dd>
                    </dl>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">ОК</button>
            </div>
        </div>
    </div>
</div>

StudentsApp.WebUI/Views/Student/Edit.cshtml
@using StudentsApp.ApplicationServices.ViewModels
@model StudentsApp.ApplicationServices.ViewModels.StudentDetailsViewModel

@{
    ViewBag.Title = "Редактирование карточки студента";
}

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "form-edit-student" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true)

        @Html.HiddenFor(model => model.StudentUserId)
        
        <div class="form-group form-group-sm">
            @Html.LabelFor(model => model.Login, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Login, new { @class = "form-control input-sm" })
            </div>
        </div>

        <div class="form-group form-group-sm">
            @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control input-sm" })
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>
        </div>

        <div class="form-group form-group-sm">
            @Html.LabelFor(model => model.SurName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.SurName, new { @class = "form-control input-sm" })
                @Html.ValidationMessageFor(model => model.SurName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Teachers, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div id="modal-add-teacher" class="modal fade" role="dialog">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title">Добавление преподавателя</h4>
                            </div>
                            <div class="modal-body">
                                <select id="select-teachers">
                                    <option></option>
                                </select>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                                <button id="btn-add-teacher" type="button" class="btn btn-primary">
                                    Добавить преподавателя
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                <input id="btn-open-add-teacher-modal" type="button" value="Добавить" class="btn-add btn-sm btn-default" data-toggle="modal" />
                <table id="studentTeachersTable" class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>Фамилия, Имя</th>
                        </tr>
                    </thead>
                    @for (int i = 0; i < Model.Teachers.Count(); i++)
                    {
                        <tr>
                            <td>
                                @{
                        var teacher = Model.Teachers[i];
                                }
                                @Html.DisplayFor(modelItem => teacher.FullName)
                            </td>
                            @Html.HiddenFor(modelItem => modelItem.Teachers[i].TeacherUserId)
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
}


<script type="text/javascript">
    $(document).ready(function () {
        $(document).on('click', '#btn-open-add-teacher-modal', function () {
            $.ajax({
                url: '@Url.Action("TeachersThatCanBeAdded", "Teacher")',
                data: { studentId: $('#StudentUserId').val() },
                cache: false,
                success: function (data) {
                    var select2Data = $.map(data.items, function (obj) {
                        obj.id = obj.TeacherUserId;
                        obj.text = obj.FullName;
                        return obj;
                    });
                    $("#select-teachers").select2({
                        placeholder: "Выбрать преподавателя",
                        data: select2Data,
                        width: 300
                    });
                    $('#modal-add-teacher').modal('show');
                }
            });
        });

        $(document).on('click', '#btn-add-teacher', function () {
            var selectedOption = $("#select-teachers").select2('data')[0];
            if (selectedOption.id) {
                var teacherCount = $('#studentTeachersTable > tbody > tr').length;
                var teacherUserIdHidden = '<input type="hidden" value="' + selectedOption.id
                    + '" name="Teachers[' + teacherCount + '].TeacherUserId"></input>';
                var teacherFullName = selectedOption.text;
                $('#studentTeachersTable').append('<tr><td>' + teacherFullName + '</td>' + teacherUserIdHidden + '</tr>');
                window.CloseDialog('modal-add-teacher');
            }
        });
    });
</script>